# Generated by Django 3.2.13 on 2022-06-14 13:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beach_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('facing', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('06', '06.00'), ('07', '07.00'), ('08', '08.00'), ('09', '09.00'), ('10', '10.00'), ('11', '11.00'), ('12', '12.00'), ('13', '13.00'), ('14', '14.00'), ('15', '15.00'), ('16', '16.00'), ('17', '17.00'), ('18', '18.00'), ('19', '19.00'), ('20', '20.00'), ('21', '21.00'), ('22', '22.00')], max_length=2)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_scheduler.beach')),
                ('surfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
