# Generated by Django 3.2.13 on 2022-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_scheduler', '0002_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50), max_length=200, unique=True),
        ),
    ]
