# Generated by Django 3.2.13 on 2022-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_scheduler', '0003_beach_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='slug',
        ),
        migrations.AlterField(
            model_name='beach',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
