# Generated by Django 3.2.13 on 2022-06-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_scheduler', '0004_auto_20220615_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='slug',
            field=models.SlugField(default='elly', unique=True),
            preserve_default=False,
        ),
    ]
