# Generated by Django 3.2.13 on 2022-06-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_scheduler', '0005_beach_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='beach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='session_scheduler.beach'),
        ),
    ]
